#!/bin/sh

swiftc themeswitchd.swift -o themeswitchd
cp nz.xie.themeswitch.plist ~/Library/LaunchAgents
sudo cp themeswitch themeswitchd /usr/local/bin/
launchctl load -w ~/Library/LaunchAgents/nz.xie.themeswitch.plist
launchctl start nz.xie.themeswitch
