#!/bin/sh

THEME=$1
BASE=~/.config/nvim/colors/

# 0 = switch to dark
# 1 = switch to light

if [[ "$THEME" == 0 ]]; then
    kitten themes --reload-in=all blazer-dark
	cp "${BASE}/blazer-dark.lua" "${BASE}/blazer.lua"
else
    kitten themes --reload-in=all blazer-light
	cp "${BASE}/blazer-light.lua" "${BASE}/blazer.lua"
fi

killall -SIGUSR1 nvim
