#!/bin/sh

THEME=$1
BASE=/Users/${USER}/.config

# 0 = switch to dark, 1 = switch to light

if [[ "$THEME" == 0 ]]; then
	# /opt/homebrew/bin/kitten themes --reload-in=all blazer-dark &> /tmp/log
	cp "$BASE/nvim/colors/blazer-dark.lua" "${BASE}/colors/blazer.lua"
	cp "$BASE/nvim/lua/lualine/themes/blazer-dark.lua" "${BASE}/lua/lualine/themes/blazer.lua"
	cp "$BASE/ghostty/config-dark" "$BASE/ghostty/config"
else
	# /opt/homebrew/bin/kitten themes --reload-in=all blazer-light &> /tmp/log
	cp "$BASE/nvim/colors/blazer-light.lua" "$BASE/colors/blazer.lua"
	cp "$BASE/nvim/lua/lualine/themes/blazer-light.lua" "$BASE/lua/lualine/themes/blazer.lua"
	cp "$BASE/ghostty/config-light" "$BASE/ghostty/config"
fi

killall -SIGUSR1 nvim
killall -SIGUSR2 ghostty
